module.exports = {
	ERR_MISSING_PASSPHRASE: 'ERR_MISSING_PASSPHRASE',
	ERR_OSSL_BAD_DECRYPT: 'ERR_OSSL_BAD_DECRYPT',
	ERR_INVALID_USERNAME: '390144',
	ERR_INVALID_KEY_FILE: 'ERR_INVALID_KEY_FILE',
};
